# kubeadm config images list --kubernetes-version v1.20.0
name: GitGoogleContainer
on:
  push:
env:
  kube_version: v1.20.5
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - name: install kubeadm
        run: |
          RELEASE="$(curl -sSL https://dl.k8s.io/release/stable.txt)"
          cd /usr/bin
          sudo curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/kubeadm
          sudo chmod +x kubeadm
          cat > ~/image.sh <<-EOF
          #!/bin/bash
          images="$(kubeadm config images list --kubernetes-version $kube_version)"
          EOF
          source ~/image.sh
          
      - name: Login in Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_IO_TOKEN }} 
      - name: Docker pull 
        run: |
          for i in $images;do
            docker pull $i;
          done 
      - name: Docker push ghcr.io
        run: |
          for i in $images;do
            docker tag  $i ghcr.io/itswl/${i##*/}
            docker push ghcr.io/itswl/${i##*/}
          done
          
      - name: Login in Docker Registry 
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         
      - name: Docke push 
        run: |
          for i in $images;do
            docker tag  $i imwl/${i##*/}
            docker push imwl/${i##*/}
          done
          
